export const adDataEn = [
  {
    title: 'Promote your brand on TikTok',
    platform: 'TikTok',
    campaignType: 'Viral Challenge',
    campaignGoal: 'Boost user-generated content using a trending hashtag',
    targetAudience: 'Gen Z, 13-24, global',
    region: 'Global',
    followers: 12000,
    participents:5,
    minEngagementRate: "2.5%",
    price: 45,
    payPerPost: 12,
    actionLabel: 'Accept Challenge',
    description: 'Reach Gen Z audiences with viral short videos and challenges. Ideal for bold, fun campaigns.',
    mediaType: 'Video',
    postDuration: '30 seconds',
    bestTimeToPost: '6 PM - 9 PM',
    recommendedFrequency: '3x/week',
    campaignStartDate: '2025-06-15',
    campaignEndDate: '2025-07-15',
    campaignDeadline: '2025-07-01',
    platformTip: 'Use trending sounds and hashtags for wider reach.',
    cta: 'Hot',
    rating: 4,
    capacity: 10,
    reserved: 7,
    socialProof: 7,
    status: 'Almost Full',
    approvalTime: "48h (auto-approve if not reviewed)",
    bonusInfo: "Extra $3 for best challenge video",
    brandName: "WaveSoda",
    brandLogo: "/brand/wavesoda.png",
  },
  {
    title: 'Instagram Beauty Campaign',
    platform: 'Instagram',
    campaignType: 'Influencer Storytelling',
    campaignGoal: 'Highlight new summer product line with authentic content',
    targetAudience: 'Beauty lovers, 18-34, EU',
    region: 'Europe',
    followers: 25000,
    participents:5,
    minEngagementRate: "3%",
    price: 80,
    payPerPost: 20,
    actionLabel: 'Accept Challenge',
    description: 'Engage beauty lovers with high-quality visuals and influencer storytelling.',
    mediaType: 'Reel',
    postDuration: '1 minute',
    bestTimeToPost: '12 PM - 2 PM',
    recommendedFrequency: '2x/week',
    campaignStartDate: '2025-06-01',
    campaignEndDate: '2025-06-30',
    campaignDeadline: '2025-06-28',
    platformTip: 'Use Reels and Stories for higher conversion.',
    cta: 'Popular',
    rating: 5,
    capacity: 6,
    reserved: 4,
    socialProof: 4,
    status: 'Open',
    approvalTime: "Manual within 24h",
    bonusInfo: "Free product pack for the best post",
    brandName: "GlowUp",
    brandLogo: "/brand/glowup.png",
  },
  {
    title: 'Pinterest Board Promotion',
    platform: 'Pinterest',
    campaignType: 'Long-Term Promotion',
    campaignGoal: 'Boost themed boards for DIY and interior trends',
    targetAudience: 'Moms, crafters, 20-44, US',
    region: 'US',
    followers: 9000,
    participents:8,
    minEngagementRate: "2%",
    price: 30,
    payPerPost: 8,
    actionLabel: 'Accept Challenge',
    description: 'Perfect for DIY, crafts, interior design, and seasonal trends with long-term visibility.',
    mediaType: 'Post',
    postDuration: 'Image-based',
    bestTimeToPost: '8 PM - 11 PM',
    recommendedFrequency: '4x/month',
    campaignStartDate: '2025-06-10',
    campaignEndDate: '2025-07-20',
    campaignDeadline: '2025-07-05',
    platformTip: 'Create themed boards with evergreen content.',
    cta: 'Trending',
    rating: 3,
    capacity: 5,
    reserved: 2,
    socialProof: 2,
    status: 'Open',
    approvalTime: "Auto",
    bonusInfo: "Best 3 pins get featured on homepage",
    brandName: "DIY Bliss",
    brandLogo: "/brand/diybliss.png",
  },
  {
    title: 'Facebook Health & Wellness Drive',
    platform: 'Facebook',
    campaignType: 'Community Awareness',
    campaignGoal: 'Increase signups for health webinar',
    targetAudience: 'Health-conscious, 25-55, local',
    region: 'California',
    followers: 18000,
    participents:12,
    minEngagementRate: "1.7%",
    price: 55,
    payPerPost: 15,
    actionLabel: 'Accept Challenge',
    description: 'Target community-focused audiences for health, fitness, and mental wellness campaigns.',
    mediaType: 'Post',
    postDuration: '1 minute',
    bestTimeToPost: '7 AM - 9 AM',
    recommendedFrequency: '1x/day',
    campaignStartDate: '2025-06-12',
    campaignEndDate: '2025-06-30',
    campaignDeadline: '2025-06-25',
    platformTip: 'Join health-related groups to boost visibility.',
    cta: 'Featured',
    rating: 4,
    capacity: 8,
    reserved: 8,
    socialProof: 8,
    status: 'Closed',
    approvalTime: "24h",
    bonusInfo: "Top performer gets $10 Amazon card",
    brandName: "HealthSpark",
    brandLogo: "/brand/healthspark.png",
  },
  {
    title: 'YouTube Gaming Shoutout',
    platform: 'YouTube',
    campaignType: 'Gaming Sponsorship',
    campaignGoal: 'Drive app installs and game downloads',
    targetAudience: 'Gamers, 13-28, worldwide',
    region: 'Worldwide',
    followers: 32000,
    participents:9,
    engagementRate: "6.2%",
    price: 110,
    payPerPost: 28,
    actionLabel: 'Accept Challenge',
    description: 'High-engagement ad read or gameplay integration for gaming and tech-related products.',
    mediaType: 'Video',
    postDuration: '2 minutes',
    bestTimeToPost: '3 PM - 6 PM',
    recommendedFrequency: '2x/week',
    campaignStartDate: '2025-06-20',
    campaignEndDate: '2025-07-20',
    campaignDeadline: '2025-07-10',
    platformTip: 'Use in-game ad placement with verbal callouts.',
    cta: 'Pro Deal',
    rating: 5,
    capacity: 15,
    reserved: 11,
    socialProof: 11,
    status: 'Open',
    approvalTime: "Manual (within 72h)",
    bonusInfo: "Free game key for best video",
    brandName: "GameNow",
    brandLogo: "/brand/gamenow.png",
  },
  // ...continue in this pattern for the rest
  // Just make sure to add the new fields as needed!
];
