export const adDataEn = [
  {
    title: 'Promote your brand on TikTok',
    platform: 'TikTok',
    followers: 12000,
    price: 45,
    payPerPost: 12,
    actionLabel: 'Accept Challenge',
    description: 'Reach Gen Z audiences with viral short videos and challenges. Ideal for bold, fun campaigns.',
    mediaType: 'Video' as const,
    postDuration: '30 seconds',
    bestTimeToPost: '6 PM - 9 PM',
    recommendedFrequency: '3x/week',
    campaignDeadline: '2025-07-01',
    platformTip: 'Use trending sounds and hashtags for wider reach.',
    cta: 'Hot',
    rating: 4,
    capacity: 10,      // <--- NEW
    reserved: 7,       // <--- NEW
  },
  {
    title: 'Instagram Beauty Campaign',
    platform: 'Instagram',
    followers: 25000,
    price: 80,
    payPerPost: 20,
    actionLabel: 'Accept Challenge',
    description: 'Engage beauty lovers with high-quality visuals and influencer storytelling.',
    mediaType: 'Reel' as const,
    postDuration: '1 minute',
    bestTimeToPost: '12 PM - 2 PM',
    recommendedFrequency: '2x/week',
    campaignDeadline: '2025-06-28',
    platformTip: 'Use Reels and Stories for higher conversion.',
    cta: 'Popular',
    rating: 5,
    capacity: 6,
    reserved: 4,
  },
  {
    title: 'Pinterest Board Promotion',
    platform: 'Pinterest',
    followers: 9000,
    price: 30,
    payPerPost: 8,
    actionLabel: 'Accept Challenge',
    description: 'Perfect for DIY, crafts, interior design, and seasonal trends with long-term visibility.',
    mediaType: 'Post' as const,
    postDuration: 'Image-based',
    bestTimeToPost: '8 PM - 11 PM',
    recommendedFrequency: '4x/month',
    campaignDeadline: '2025-07-05',
    platformTip: 'Create themed boards with evergreen content.',
    cta: 'Trending',
    rating: 3,
    capacity: 5,
    reserved: 2,
  },
  {
    title: 'Facebook Health & Wellness Drive',
    platform: 'Facebook',
    followers: 18000,
    price: 55,
    payPerPost: 15,
    actionLabel: 'Accept Challenge',
    description: 'Target community-focused audiences for health, fitness, and mental wellness campaigns.',
    mediaType: 'Post' as const,
    postDuration: '1 minute',
    bestTimeToPost: '7 AM - 9 AM',
    recommendedFrequency: '1x/day',
    campaignDeadline: '2025-06-25',
    platformTip: 'Join health-related groups to boost visibility.',
    cta: 'Featured',
    rating: 4,
    capacity: 8,
    reserved: 8,
  },
  {
    title: 'YouTube Gaming Shoutout',
    platform: 'YouTube',
    followers: 32000,
    price: 110,
    payPerPost: 28,
    actionLabel: 'Accept Challenge',
    description: 'High-engagement ad read or gameplay integration for gaming and tech-related products.',
    mediaType: 'Video' as const,
    postDuration: '2 minutes',
    bestTimeToPost: '3 PM - 6 PM',
    recommendedFrequency: '2x/week',
    campaignDeadline: '2025-07-10',
    platformTip: 'Use in-game ad placement with verbal callouts.',
    cta: 'Pro Deal',
    rating: 5,
    capacity: 15,
    reserved: 11,
  },
  {
    title: 'Lifestyle Reels on Instagram',
    platform: 'Instagram',
    followers: 14000,
    price: 60,
    payPerPost: 16,
    actionLabel: 'Accept Challenge',
    description: 'Trendy reel content promoting lifestyle, travel, or fashion with visual appeal.',
    mediaType: 'Reel' as const,
    postDuration: '45 seconds',
    bestTimeToPost: '10 AM - 1 PM',
    recommendedFrequency: '3x/week',
    campaignDeadline: '2025-07-02',
    platformTip: 'Use visual hooks in the first 3 seconds.',
    cta: 'Hot',
    rating: 4,
    capacity: 7,
    reserved: 5,
  },
  {
    title: 'TikTok Comedy Series Integration',
    platform: 'TikTok',
    followers: 50000,
    price: 130,
    payPerPost: 33,
    actionLabel: 'Accept Challenge',
    description: 'Sponsor a comedy skit for viral engagement and creative storytelling.',
    mediaType: 'Video' as const,
    postDuration: '1 minute',
    bestTimeToPost: '6 PM - 9 PM',
    recommendedFrequency: '2x/week',
    campaignDeadline: '2025-06-30',
    platformTip: 'Collaborate with meme creators for organic feel.',
    cta: 'Premium',
    rating: 5,
    capacity: 12,
    reserved: 3,
  },
  {
    title: 'Pinterest Fitness Challenge Campaign',
    platform: 'Pinterest',
    followers: 10000,
    price: 35,
    payPerPost: 10,
    actionLabel: 'Accept Challenge',
    description: 'Target fitness planners and pin collectors with interactive, trackable boards.',
    mediaType: 'Post' as const,
    postDuration: 'Image-based',
    bestTimeToPost: '8 PM - 11 PM',
    recommendedFrequency: '1x/week',
    campaignDeadline: '2025-07-07',
    platformTip: 'Offer downloadable workout templates.',
    cta: 'Recommended',
    rating: 3,
    capacity: 10,
    reserved: 5,
  },
  {
    title: 'Facebook Local Business Feature',
    platform: 'Facebook',
    followers: 15000,
    price: 40,
    payPerPost: 11,
    actionLabel: 'Accept Challenge',
    description: 'Great for geotargeted exposure of restaurants, salons, or local events.',
    mediaType: 'Post' as const,
    postDuration: '1 minute',
    bestTimeToPost: '7 AM - 10 AM',
    recommendedFrequency: '5x/month',
    campaignDeadline: '2025-06-22',
    platformTip: 'Use geo-targeted tags and city names.',
    cta: 'Local Star',
    rating: 4,
    capacity: 7,
    reserved: 4,
  },
  {
    title: 'Instagram Tech Product Launch',
    platform: 'Instagram',
    followers: 27000,
    price: 95,
    payPerPost: 24,
    actionLabel: 'Accept Challenge',
    description: 'Build anticipation with influencer unboxing, carousel posts, and story Q&A.',
    mediaType: 'Story' as const,
    postDuration: '15 seconds',
    bestTimeToPost: '1 PM - 4 PM',
    recommendedFrequency: '2x/week',
    campaignDeadline: '2025-06-27',
    platformTip: 'Tease upcoming features with countdown stickers.',
    cta: 'Launch Special',
    rating: 5,
    capacity: 4,
    reserved: 2,
  },
];
