export const adDataFa = [
  {
    title: 'تبلیغ برند شما در تیک‌تاک',
    platform: 'TikTok',
    followers: 12000,
    price: 45,
    payPerPost: 12,
    actionLabel: 'پذیرش چالش',
    description: 'دسترسی به نسل Z با ویدیوهای کوتاه و چالش‌های وایرال. مناسب برای کمپین‌های پر انرژی و خلاقانه.',
    mediaType: 'Video' as const,
    postDuration: '۳۰ ثانیه',
    bestTimeToPost: '۱۸:۰۰ تا ۲۱:۰۰',
    recommendedFrequency: '۳ بار در هفته',
    engagementRate: '۶.۲٪',
    campaignDeadline: '۲۰۲۵/۰۷/۰۱',
    platformTip: 'از صداها و هشتگ‌های ترند استفاده کنید.',
    cta: 'داغ',
    rating: 4,
  },
  {
    title: 'کمپین زیبایی اینستاگرام',
    platform: 'Instagram',
    followers: 25000,
    price: 80,
    payPerPost: 20,
    actionLabel: 'پذیرش چالش',
    description: 'جذب علاقه‌مندان به زیبایی با تصاویر با کیفیت و داستان‌سرایی تأثیرگذار.',
    mediaType: 'Reel' as const,
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۱۲:۰۰ تا ۱۴:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    engagementRate: '۸.۱٪',
    campaignDeadline: '۲۰۲۵/۰۶/۲۸',
    platformTip: 'از Reels و Stories برای تعامل بیشتر استفاده کنید.',
    cta: 'محبوب',
    rating: 5,
  },
  {
    title: 'تبلیغ در پینترست',
    platform: 'Pinterest',
    followers: 9000,
    price: 30,
    payPerPost: 8,
    actionLabel: 'پذیرش چالش',
    description: 'مناسب برای DIY، دکوراسیون داخلی، و محتوای ترند فصلی با ماندگاری بالا.',
    mediaType: 'Post' as const,
    postDuration: 'تصویری',
    bestTimeToPost: '۲۰:۰۰ تا ۲۳:۰۰',
    recommendedFrequency: '۴ بار در ماه',
    engagementRate: '۵.۵٪',
    campaignDeadline: '۲۰۲۵/۰۷/۰۵',
    platformTip: 'بردهایی با موضوعات خاص و محتوای همیشگی ایجاد کنید.',
    cta: 'رو به رشد',
    rating: 3,
  },
  {
    title: 'سلامت و تندرستی در فیسبوک',
    platform: 'Facebook',
    followers: 18000,
    price: 55,
    payPerPost: 15,
    actionLabel: 'پذیرش چالش',
    description: 'هدف‌گیری جوامع برای کمپین‌های مرتبط با سلامت، تناسب اندام و روان.',
    mediaType: 'Post' as const,
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۰۷:۰۰ تا ۰۹:۰۰',
    recommendedFrequency: '۱ بار در روز',
    engagementRate: '۴.۸٪',
    campaignDeadline: '۲۰۲۵/۰۶/۲۵',
    platformTip: 'در گروه‌های مرتبط با سلامت عضو شوید.',
    cta: 'ویژه',
    rating: 4,
  },
  {
    title: 'شات‌اوت گیمینگ یوتیوب',
    platform: 'YouTube',
    followers: 32000,
    price: 110,
    payPerPost: 28,
    actionLabel: 'پذیرش چالش',
    description: 'تبلیغات داخل ویدیو یا گیم‌پلی برای محصولات مرتبط با گیم و تکنولوژی.',
    mediaType: 'Video' as const,
    postDuration: '۲ دقیقه',
    bestTimeToPost: '۱۵:۰۰ تا ۱۸:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    engagementRate: '۹.۴٪',
    campaignDeadline: '۲۰۲۵/۰۷/۱۰',
    platformTip: 'از تبلیغات داخل بازی با اشاره مستقیم استفاده کنید.',
    cta: 'پیشنهاد حرفه‌ای',
    rating: 5,
  },
  {
    title: 'Reel لایف‌استایل اینستاگرام',
    platform: 'Instagram',
    followers: 14000,
    price: 60,
    payPerPost: 16,
    actionLabel: 'پذیرش چالش',
    description: 'محتوای خلاقانه در سبک زندگی، سفر یا مد با جذابیت بصری.',
    mediaType: 'Reel' as const,
    postDuration: '۴۵ ثانیه',
    bestTimeToPost: '۱۰:۰۰ تا ۱۳:۰۰',
    recommendedFrequency: '۳ بار در هفته',
    engagementRate: '۷.۲٪',
    campaignDeadline: '۲۰۲۵/۰۷/۰۲',
    platformTip: 'در ۳ ثانیه اول توجه مخاطب را جلب کنید.',
    cta: 'داغ',
    rating: 4,
  },
  {
    title: 'طنز سریالی تیک‌تاک',
    platform: 'TikTok',
    followers: 50000,
    price: 130,
    payPerPost: 33,
    actionLabel: 'پذیرش چالش',
    description: 'اسپانسرینگ محتوای طنز با قابلیت وایرال بالا و داستان‌گویی خلاقانه.',
    mediaType: 'Video' as const,
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۱۸:۰۰ تا ۲۱:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    engagementRate: '۱۰.۵٪',
    campaignDeadline: '۲۰۲۵/۰۶/۳۰',
    platformTip: 'با سازندگان طنز همکاری کنید.',
    cta: 'پریمیوم',
    rating: 5,
  },
  {
    title: 'چالش تناسب اندام در پینترست',
    platform: 'Pinterest',
    followers: 10000,
    price: 35,
    payPerPost: 10,
    actionLabel: 'پذیرش چالش',
    description: 'جذب علاقه‌مندان به فیتنس با بردهای قابل پیگیری و تعاملی.',
    mediaType: 'Post' as const,
    postDuration: 'تصویری',
    bestTimeToPost: '۲۰:۰۰ تا ۲۳:۰۰',
    recommendedFrequency: '۱ بار در هفته',
    engagementRate: '۴.۹٪',
    campaignDeadline: '۲۰۲۵/۰۷/۰۷',
    platformTip: 'قالب‌های تمرینی قابل دانلود ارائه دهید.',
    cta: 'پیشنهاد شده',
    rating: 3,
  },
  {
    title: 'معرفی کسب‌و‌کار محلی در فیسبوک',
    platform: 'Facebook',
    followers: 15000,
    price: 40,
    payPerPost: 11,
    actionLabel: 'پذیرش چالش',
    description: 'مناسب برای معرفی رستوران، آرایشگاه یا رویدادهای محلی.',
    mediaType: 'Post' as const,
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۰۷:۰۰ تا ۱۰:۰۰',
    recommendedFrequency: '۵ بار در ماه',
    engagementRate: '۵.۳٪',
    campaignDeadline: '۲۰۲۵/۰۶/۲۲',
    platformTip: 'از برچسب‌های مکان و نام شهر استفاده کنید.',
    cta: 'ستاره محلی',
    rating: 4,
  },
  {
    title: 'عرضه محصول فناوری در اینستاگرام',
    platform: 'Instagram',
    followers: 27000,
    price: 95,
    payPerPost: 24,
    actionLabel: 'پذیرش چالش',
    description: 'ایجاد هیجان با آنباکسینگ، پست‌های چرخشی و Q&A در استوری.',
    mediaType: 'Story' as const,
    postDuration: '۱۵ ثانیه',
    bestTimeToPost: '۱۳:۰۰ تا ۱۶:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    engagementRate: '۸.۹٪',
    campaignDeadline: '۲۰۲۵/۰۶/۲۷',
    platformTip: 'با استیکر شمارش معکوس ویژگی‌ها را معرفی کنید.',
    cta: 'ویژه راه‌اندازی',
    rating: 5,
  },
];