export const adDataFa = [
  {
    title: 'تبلیغ برند شما در تیک‌تاک',
    platform: 'TikTok',
    followers: 12000,
    price: 45,
    payPerPost: 12,
    actionLabel: 'پذیرش چالش',
    description: 'دسترسی به نسل Z با ویدیوهای کوتاه و چالش‌های وایرال. مناسب برای کمپین‌های پر انرژی و خلاقانه.',
    mediaType: 'Video',
    postDuration: '۳۰ ثانیه',
    bestTimeToPost: '۱۸:۰۰ تا ۲۱:۰۰',
    recommendedFrequency: '۳ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۷/۰۱',
    campaignStartDate: '۲۰۲۵/۰۶/۲۰',
    campaignEndDate: '۲۰۲۵/۰۷/۰۵',
    approvalTime: 'تا ۴۸ ساعت پس از ارسال',
    platformTip: 'از صداها و هشتگ‌های ترند استفاده کنید.',
    cta: 'داغ',
    rating: 4,
    capacity: 10,
    reserved: 7,
    bonusInfo: 'تا ۲۰٪ جایزه بیشتر برای ویدیوهای وایرال',
    socialProof: 15,
    status: "Open",
  },
  {
    title: 'کمپین زیبایی اینستاگرام',
    platform: 'Instagram',
    followers: 25000,
    price: 80,
    payPerPost: 20,
    actionLabel: 'پذیرش چالش',
    description: 'جذب علاقه‌مندان به زیبایی با تصاویر با کیفیت و داستان‌سرایی تأثیرگذار.',
    mediaType: 'Reel',
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۱۲:۰۰ تا ۱۴:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۶/۲۸',
    campaignStartDate: '۲۰۲۵/۰۶/۱۵',
    campaignEndDate: '۲۰۲۵/۰۶/۲۹',
    approvalTime: '۲۴ ساعت',
    platformTip: 'از Reels و Stories برای تعامل بیشتر استفاده کنید.',
    cta: 'محبوب',
    rating: 5,
    capacity: 6,
    reserved: 4,
    bonusInfo: 'پاداش ویژه برای پست‌های خلاقانه',
    socialProof: 10,
    status: "Almost Full",
  },
  {
    title: 'تبلیغ در پینترست',
    platform: 'Pinterest',
    followers: 9000,
    price: 30,
    payPerPost: 8,
    actionLabel: 'پذیرش چالش',
    description: 'مناسب برای DIY، دکوراسیون داخلی، و محتوای ترند فصلی با ماندگاری بالا.',
    mediaType: 'Post',
    postDuration: 'تصویری',
    bestTimeToPost: '۲۰:۰۰ تا ۲۳:۰۰',
    recommendedFrequency: '۴ بار در ماه',
    campaignDeadline: '۲۰۲۵/۰۷/۰۵',
    campaignStartDate: '۲۰۲۵/۰۶/۲۵',
    campaignEndDate: '۲۰۲۵/۰۷/۱۰',
    approvalTime: '۷۲ ساعت',
    platformTip: 'بردهایی با موضوعات خاص و محتوای همیشگی ایجاد کنید.',
    cta: 'رو به رشد',
    rating: 3,
    capacity: 5,
    reserved: 2,
    socialProof: 3,
    status: "Open",
  },
  {
    title: 'سلامت و تندرستی در فیسبوک',
    platform: 'Facebook',
    followers: 18000,
    price: 55,
    payPerPost: 15,
    actionLabel: 'پذیرش چالش',
    description: 'هدف‌گیری جوامع برای کمپین‌های مرتبط با سلامت، تناسب اندام و روان.',
    mediaType: 'Post',
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۰۷:۰۰ تا ۰۹:۰۰',
    recommendedFrequency: '۱ بار در روز',
    campaignDeadline: '۲۰۲۵/۰۶/۲۵',
    campaignStartDate: '۲۰۲۵/۰۶/۱۰',
    campaignEndDate: '۲۰۲۵/۰۶/۲۶',
    approvalTime: '۴۸ ساعت',
    platformTip: 'در گروه‌های مرتبط با سلامت عضو شوید.',
    cta: 'ویژه',
    rating: 4,
    capacity: 8,
    reserved: 8,
    bonusInfo: 'امتیاز ویژه برای همکاری‌های بلندمدت',
    socialProof: 12,
    status: "Closed",
  },
  {
    title: 'شات‌اوت گیمینگ یوتیوب',
    platform: 'YouTube',
    followers: 32000,
    price: 110,
    payPerPost: 28,
    actionLabel: 'پذیرش چالش',
    description: 'تبلیغات داخل ویدیو یا گیم‌پلی برای محصولات مرتبط با گیم و تکنولوژی.',
    mediaType: 'Video',
    postDuration: '۲ دقیقه',
    bestTimeToPost: '۱۵:۰۰ تا ۱۸:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۷/۱۰',
    campaignStartDate: '۲۰۲۵/۰۷/۰۱',
    campaignEndDate: '۲۰۲۵/۰۷/۲۲',
    approvalTime: '۵ روز',
    platformTip: 'از تبلیغات داخل بازی با اشاره مستقیم استفاده کنید.',
    cta: 'پیشنهاد حرفه‌ای',
    rating: 5,
    capacity: 15,
    reserved: 11,
    bonusInfo: 'پاداش برای ویدیوهای پربازدید',
    socialProof: 20,
    status: "Open",
  },
  {
    title: 'Reel لایف‌استایل اینستاگرام',
    platform: 'Instagram',
    followers: 14000,
    price: 60,
    payPerPost: 16,
    actionLabel: 'پذیرش چالش',
    description: 'محتوای خلاقانه در سبک زندگی، سفر یا مد با جذابیت بصری.',
    mediaType: 'Reel',
    postDuration: '۴۵ ثانیه',
    bestTimeToPost: '۱۰:۰۰ تا ۱۳:۰۰',
    recommendedFrequency: '۳ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۷/۰۲',
    campaignStartDate: '۲۰۲۵/۰۶/۲۰',
    campaignEndDate: '۲۰۲۵/۰۷/۰۳',
    approvalTime: '۳۶ ساعت',
    platformTip: 'در ۳ ثانیه اول توجه مخاطب را جلب کنید.',
    cta: 'داغ',
    rating: 4,
    capacity: 7,
    reserved: 5,
    status: "Open",
    socialProof: 7,
  },
  {
    title: 'طنز سریالی تیک‌تاک',
    platform: 'TikTok',
    followers: 50000,
    price: 130,
    payPerPost: 33,
    actionLabel: 'پذیرش چالش',
    description: 'اسپانسرینگ محتوای طنز با قابلیت وایرال بالا و داستان‌گویی خلاقانه.',
    mediaType: 'Video',
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۱۸:۰۰ تا ۲۱:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۶/۳۰',
    campaignStartDate: '۲۰۲۵/۰۶/۱۵',
    campaignEndDate: '۲۰۲۵/۰۷/۰۴',
    approvalTime: '۴۸ ساعت',
    platformTip: 'با سازندگان طنز همکاری کنید.',
    cta: 'پریمیوم',
    rating: 5,
    capacity: 12,
    reserved: 3,
    status: "Open",
    socialProof: 5,
  },
  {
    title: 'چالش تناسب اندام در پینترست',
    platform: 'Pinterest',
    followers: 10000,
    price: 35,
    payPerPost: 10,
    actionLabel: 'پذیرش چالش',
    description: 'جذب علاقه‌مندان به فیتنس با بردهای قابل پیگیری و تعاملی.',
    mediaType: 'Post',
    postDuration: 'تصویری',
    bestTimeToPost: '۲۰:۰۰ تا ۲۳:۰۰',
    recommendedFrequency: '۱ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۷/۰۷',
    campaignStartDate: '۲۰۲۵/۰۶/۲۵',
    campaignEndDate: '۲۰۲۵/۰۷/۱۰',
    approvalTime: '۷۲ ساعت',
    platformTip: 'قالب‌های تمرینی قابل دانلود ارائه دهید.',
    cta: 'پیشنهاد شده',
    rating: 3,
    capacity: 10,
    reserved: 5,
    status: "Open",
    socialProof: 2,
  },
  {
    title: 'معرفی کسب‌و‌کار محلی در فیسبوک',
    platform: 'Facebook',
    followers: 15000,
    price: 40,
    payPerPost: 11,
    actionLabel: 'پذیرش چالش',
    description: 'مناسب برای معرفی رستوران، آرایشگاه یا رویدادهای محلی.',
    mediaType: 'Post',
    postDuration: '۱ دقیقه',
    bestTimeToPost: '۰۷:۰۰ تا ۱۰:۰۰',
    recommendedFrequency: '۵ بار در ماه',
    campaignDeadline: '۲۰۲۵/۰۶/۲۲',
    campaignStartDate: '۲۰۲۵/۰۶/۰۷',
    campaignEndDate: '۲۰۲۵/۰۶/۲۳',
    approvalTime: '۲ روز',
    platformTip: 'از برچسب‌های مکان و نام شهر استفاده کنید.',
    cta: 'ستاره محلی',
    rating: 4,
    capacity: 7,
    reserved: 4,
    status: "Open",
    socialProof: 8,
  },
  {
    title: 'عرضه محصول فناوری در اینستاگرام',
    platform: 'Instagram',
    followers: 27000,
    price: 95,
    payPerPost: 24,
    actionLabel: 'پذیرش چالش',
    description: 'ایجاد هیجان با آنباکسینگ، پست‌های چرخشی و Q&A در استوری.',
    mediaType: 'Story',
    postDuration: '۱۵ ثانیه',
    bestTimeToPost: '۱۳:۰۰ تا ۱۶:۰۰',
    recommendedFrequency: '۲ بار در هفته',
    campaignDeadline: '۲۰۲۵/۰۶/۲۷',
    campaignStartDate: '۲۰۲۵/۰۶/۱۰',
    campaignEndDate: '۲۰۲۵/۰۶/۲۸',
    approvalTime: '۴۸ ساعت',
    platformTip: 'با استیکر شمارش معکوس ویژگی‌ها را معرفی کنید.',
    cta: 'ویژه راه‌اندازی',
    rating: 5,
    capacity: 4,
    reserved: 2,
    status: "Almost Full",
    socialProof: 3,
  },
];
